- hosts: all
  become: true
  
  tasks:
  - name: Install packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
        - httpd
        - wget
        - unzip
        - epel-release
        - mysql
        - mariadb
        - mariadb-server

  - name: Install PHP 7.4 from Remi repository
    yum:
      name: php
      state: present
  
  - name: Enable Remi repository for PHP 7.4
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present

  - name: Enable PHP 7.4 in Remi repository
    yum_repository:
      name: remi-php74
      description: Remi's PHP 7.4 RPM repository for Enterprise Linux 7 - $basearch
      baseurl: https://rpms.remirepo.net/enterprise/7/php74/$basearch/
      gpgcheck: yes
      gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
      enabled: yes

  - name: Install PHP MySQL extension
    yum:
      name: php-mysql
      state: present

  - name: Download WordPress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/latest.tar.gz

  - name: Extract WordPress
    unarchive:
      src: /tmp/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
      extra_opts: [--strip-components=1] # --> equivalent to 'mv wordpress/* /var/www/html/'
    notify:
        - Restart Apache

  - name: Set ownership for WordPress directory
    file:
      path: /var/www/html/
      owner: apache
      group: apache
      recurse: yes

  - name: Start Apache
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Start and enable MariaDB
    service:
      name: mariadb
      state: started
      enabled: yes
  
  handlers:
    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted
  